Fix validation test 'ftd_remaillage'

diff --git a/share/Validation/Rapports_automatiques/Multiphase/Front_tracking_discontinu/ftd_remaillage/src/pre_run_vdf b/share/Validation/Rapports_automatiques/Multiphase/Front_tracking_discontinu/ftd_remaillage/src/pre_run_vdf
--- a/share/Validation/Rapports_automatiques/Multiphase/Front_tracking_discontinu/ftd_remaillage/src/pre_run_vdf
+++ b/share/Validation/Rapports_automatiques/Multiphase/Front_tracking_discontinu/ftd_remaillage/src/pre_run_vdf
@@ -1,3 +1,16 @@
-make_PAR.data FTD_remaillage_vdf 
-sed 's/lata\/post/lata\/par_post/g' PAR_FTD_remaillage_vdf.data > tmp
-sed 's/PARALLEL RUNS/PARALLEL ONLY 4/g' tmp > PAR_FTD_remaillage_vdf.data
+#!/bin/bash
+
+JDD="FTD_remaillage_vdf"
+JDD_PAR="PAR_${JDD}"
+
+make_PAR.data ${JDD}
+
+if [[ ! -f "${JDD_PAR}.data" ]]
+then
+  echo -e "Error: the jdd '${JDD_PAR}' does not exist !"
+  exit 1
+fi
+
+sed -ri 's/lata\/post/lata\/par_post/g' ${JDD_PAR}.data
+
+sed -ri 's/PARALLEL RUNS/PARALLEL ONLY 4/g' ${JDD_PAR}.data 
